-- 코드를 작성해주세요
SELECT distinct B.ID , B.EMAIL, B.FIRST_NAME, B.LAST_NAME FROM SKILLCODES A, DEVELOPERS B
WHERE conv(SKILL_CODE,10,2) DIV (SELECT conv(CODE,10,2) FROM SKILLCODES where NAME="Python") % 10=1 or conv(SKILL_CODE,10,2) DIV (SELECT conv(CODE,10,2) FROM SKILLCODES where NAME="C#")%10=1
ORDER BY ID ASC;